sudo: false

language: java

os:
  - linux

addons:
  apt:
    packages:
    - ant

jdk:
  - oraclejdk8

script:
  - export SRC=$PWD
  - cd $HOME
  - export TAG=1.6.12
  - wget https://github.com/arduino/Arduino/archive/$TAG.zip
  - unzip $TAG.zip
  - rm $TAG.zip
  - export arduino_dir=Arduino-$TAG
  - pushd $arduino_dir/build
  - echo "" | ant build
  - pushd shared/tools
  - mkdir -p ESP8266FS
  - rsync -a $SRC/ ESP8266FS/
  - pushd ESP8266FS
  - ./make.sh
  - popd && popd && popd
